# Generated by Django 4.1.7 on 2023-03-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ganadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fechalimite', models.DateTimeField()),
                ('fechadellegada', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='autos',
            new_name='categoria',
        ),
    ]
